### ISSUE TITLE
Does this script work?

### ISSUE THREAD

**Issue by bhanu2217** [liamfiddler/phpdoc-to-githubwiki#1]
Is this script still working?

**Comment by liamfiddler** [comment]
Hi @bhanu2217 !

I haven't written any significant PHP in over a year so I haven't given this script much love lately 😞 

I just tested it on my machine it it appears to be missing a dependency for PHPDoc. I can't recall if it should be installed globally or if it should be automatically installed by the script. I'll investigate over the next few days and get back to you.

Or if you've got some time feel free to fork the repo, fix the issue, and submit a pull request ❤️

**Comment by liamfiddler** [comment]
Hi again @bhanu2217 - just a quick one to let you know that the script is working.

Previously the script just assumed you had all the required dependencies, but I've just pushed an update so now it will check if you have PHP & Git, and will download a local version of PHPDocumentor if you don't already have it installed globally.

Here's the output i got when I ran the script; give it a shot and let me know if you're still having issues 😄 

<img width="1263" alt="screen shot 2018-09-30 at 3 03 09 pm" src="https://user-images.githubusercontent.com/4485449/46253581-614dfa80-c4c2-11e8-9b6d-3995508cc619.png">

**Comment by bhanu2217** [comment]
Thank You :-)

**Comment by Arjunladybird** [comment]
i have ran the script successfully and got below out put but i cant see any changes in github wiki
Please check the below screenshot
http://prntscr.com/lw0qek

**Comment by liamfiddler** [comment]
Hi @Arjunladybird

It looks like you haven't configured Git with a push default. I recommend you follow the instructions in the screenshot you posted. You can find an explanation of the options at https://git-scm.com/docs/git-config.html#git-config-pushdefault

Although this isn't an issue with this project, we can probably avoid the message by specifying which branch we're trying to push in the script. I've created issue #2 to handle this.
